### ISSUE TITLE
Path to GUESS

### ISSUE THREAD

**Issue by mingfang618** [chr1swallace/GUESSFM#12]
Dear Swallace,

I just run GUESSFM, but when I run the following command, I could not find the path of "GUESS", may I have general idear how can I define the path of "GUESS", which puzzled me until now. Without the path I am not able to continue the running.

Thank you!

run.bvs(X,Y,gdir=mydir,
        tag.r2=0.95,           # maximum r2 between SNPs to be modelled
        guess.command="GUESS", # /path/to/GUESS
        nexp=3,                # expected number of causal variants, an overestimate
        nsave=1000)            # number of best models to save

**Comment by chr1swallace** [comment]
Have you installed GUESS?  What is your operating system?

**Comment by mingfang618** [comment]
I have "R2GUESS" and "GUESSFM" installed, but I did not install "GUESS". Do I need to install "GUESS" too? I am using Linux server. 
Thanks!

**Comment by chr1swallace** [comment]
It appears R2GUESS installs GUESS.  Looking at R2GUESS, try

```
pack.root <- system.file(package = "R2GUESS")
ESS.directory <- file.path(pack.root, "bin", .Platform$r_arch)
guess.executable <- ifelse(.Platform$OS.type == "unix", "GUESS", 
        "GUESS.exe")
file.path(ESS.directory, guess.executable)
```

Does that give you a proper executable?  If so, I will add that as a default path to GUESS.

Thanks for all these issues, very useful to know what I have failed to document well and be able to fix it!

**Comment by mingfang618** [comment]
It seemed to make GUESS excutable, but still have "shared libraries" problem below. Thanks!

*\* /home/users/m/f/mfang/R/x86_64-unknown-linux-gnu-library/3.0/R2GUESS/bin//GUESS: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory

**

**Comment by chr1swallace** [comment]
Can you run GUESS through R2GUESS?

**Comment by mingfang618** [comment]
I am having a look now... 
But I do not know exactly how to do that, could you provide some clue?
Thanks!

-Ming

**Comment by chr1swallace** [comment]
I think it's the function `R2GUESS::R2GUESS()`

**Comment by mingfang618** [comment]
I found the solutions, your path is perfect, but I should load "gsl" module when running. 
Thanks!
