### ISSUE TITLE
Binary traits

### ISSUE THREAD

**Issue by mingfang618** [chr1swallace/GUESSFM#14]
I am stating to apply the method to my dataset, which is a binary disease trait. I am wondering that does the method assume linear model for binary trait too (i.e. use 0 and 1 as phenotypes)? Thanks!

**Comment by chr1swallace** [comment]
GUESS will run with a 0/1 linear model but best models will be refit under a GLM.

**Comment by mingfang618** [comment]
Thank you for confirming that :-)
