### ISSUE TITLE
Imputed dasage file

### ISSUE THREAD

**Issue by mingfang618** [chr1swallace/GUESSFM#15]
When I applied the method to my imputed dosage dataset, which produced an error when running. I donot know what does the error mean and how can I fix my dataset? My dataset contains about 60,000 individuals with many rare variants, so it is often the allele frequency is extreamly low. Thanks!

> run.bvs(X ,Y ,gdir= "/home/ulg/genan/mfang/guess",tag.r2=0.95, guess.command=path,
> +
> - nexp=3,nsave=1000)

Error in tag(X, tag.threshold = tag.r2) :
  some SNPs have zero standard deviation (missing HWE stat). Please fix and rerun

**Comment by chr1swallace** [comment]
I haven't considered imputed dosages and I am not clear how they should be represented in SnpStats whose data structure I depend on.  I can look, but usually, it means some of your SNPs have a constant genotype across all individuals and are not informative - can you please check this first?

**Comment by mingfang618** [comment]
I have a quick check of the SnpStats, the suitable format is below. I think it is not able to analyze dosage file.

### The data file must be tab("\t"), space(" ") or semi-colon(";")-delimited, with column names (if exist) in the first row. Alleles should be separated with a slash "/", and column names cannot begin with a number.

Missings can be codified either with string "NA", NULL (empty) values, or a new specified string.
An example of a data file could be the following:
id  snp1    snp2    snp3    snp4    status  sex age cat.bmi
1   C/C G/G A/G C/C Co  Female  74  [25.9,29.0)
2   C/C G/G A/A C/G Co  Male    50  [16.0,23.6)
3   C/C G/G A/G C/G Co  Female  64  [16.0,23.6)
4   C/C G/G A/A C/C Ca  Male    67  [16.0,23.6)
5   C/C G/G G/G C/C Co  Female  80  [29.0,52.2]
6   C/C G/G A/G C/C Co  Male    79  [29.0,52.2]
7   C/C G/G A/G C/G Ca  Male    83  [16.0,23.6)
8   C/C G/G G/G C/C Co  Male    53  [23.6,25.9)
9   C/C NA  G/G C/G Ca  Male    70  [25.9,29.0)
10  C/T G/G G/G C/G Ca  Male    62  [25.9,29.0)_

**Comment by chr1swallace** [comment]
Snpstats can certainly read imputed data (including uncertain genotypes) from impute2, so it allows more formats.

On 21 April 2016 06:47:01 BST, mingfang618 notifications@github.com wrote:

> I have a quick check of the SnpStats, the suitable format is below. I
> think it is not able to analyze dosage file.
> 
> ### The data file must be tab("\t"), space(" ") or
> 
> semi-colon(";")-delimited, with column names (if exist) in the first
> row. Alleles should be separated with a slash "/", and column names
> cannot begin with a number. 
> Missings can be codified either with string "NA", NULL (empty) values,
> or a new specified string.
> An example of a data file could be the following:
> id snp1    snp2    snp3    snp4    status  sex age cat.bmi
> 1  C/C G/G A/G C/C Co  Female  74  [25.9,29.0)
> 2  C/C G/G A/A C/G Co  Male    50  [16.0,23.6)
> 3  C/C G/G A/G C/G Co  Female  64  [16.0,23.6)
> 4  C/C G/G A/A C/C Ca  Male    67  [16.0,23.6)
> 5  C/C G/G G/G C/C Co  Female  80  [29.0,52.2]
> 6  C/C G/G A/G C/C Co  Male    79  [29.0,52.2]
> 7  C/C G/G A/G C/G Ca  Male    83  [16.0,23.6)
> 8  C/C G/G G/G C/C Co  Male    53  [23.6,25.9)
> 9  C/C NA  G/G C/G Ca  Male    70  [25.9,29.0)
> 10 C/T G/G G/G C/G Ca  Male    62  [25.9,29.0)_
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/chr1swallace/GUESSFM/issues/15#issuecomment-212753022

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mingfang618** [comment]
Is it easy to adapt the GUESSFM for the dosage data? Or I should adapt my dataset to genotype data?

**Comment by chr1swallace** [comment]
It's about the representation of those data in snpstats. One simple method would be to remove the poorly imputed SNPs (low information, for example) which can cause problems for multi SNP models, and what remains should be very close to integers, so just round to a matrix of 0, 1, 2.

On 21 April 2016 07:24:10 BST, mingfang618 notifications@github.com wrote:

> Is it easy to adapt the GUESSFM for the dosage data? Or I should adapt
> my dataset to genotype data?
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/chr1swallace/GUESSFM/issues/15#issuecomment-212765139

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mingfang618** [comment]
Got it, thanks!

**Comment by chr1swallace** [comment]
I've checked, and snpStats has functions for reading in data directly from beagle, impute2 and mach (`read.beagle`, `read.impute`, `read.mach`).  How did you do your imputation?

**Comment by mingfang618** [comment]
My data is impute2 format...

**Comment by chr1swallace** [comment]
Then you should read it into R with read.impute() and not use dosages at all. Snpstats can handle the uncertain genotypes.

On 21 April 2016 08:58:24 BST, mingfang618 notifications@github.com wrote:

> My data is impute2 format...
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/chr1swallace/GUESSFM/issues/15#issuecomment-212793134

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mingfang618** [comment]
But what is the input format for "X" like, where X <-new("SnpMatrix",matrix(as.raw(as.matrix(X)+1),nrow=nrow(X),dimnames=dimnames(X))), 
previousely we cut the data into genotype matrix, but now how can I use "new" function with impute data to make a "X" matrix for the input of run.bvs.

**Comment by chr1swallace** [comment]
The thing you read in should be X, in snpstats format.

On 21 April 2016 09:55:58 BST, mingfang618 notifications@github.com wrote:

> But what is the input format for "X" like, where X
> <-new("SnpMatrix",matrix(as.raw(as.matrix(X)+1),nrow=nrow(X),dimnames=dimnames(X))),
> 
> previousely we cut the data into genotype matrix, but now how can I use
> "new" function with impute data to make a "X" matrix for the input of
> run.bvs. 
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/chr1swallace/GUESSFM/issues/15#issuecomment-212819271

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mingfang618** [comment]
Perfect, I will try.

At 2016-04-21 17:18:45, "Chris Wallace" notifications@github.com wrote:
The thing you read in should be X, in snpstats format.

On 21 April 2016 09:55:58 BST, mingfang618 notifications@github.com wrote:

> But what is the input format for "X" like, where X
> <-new("SnpMatrix",matrix(as.raw(as.matrix(X)+1),nrow=nrow(X),dimnames=dimnames(X))),
> 
> previousely we cut the data into genotype matrix, but now how can I use
> "new" function with impute data to make a "X" matrix for the input of
> run.bvs.
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/chr1swallace/GUESSFM/issues/15#issuecomment-212819271

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
