### ISSUE TITLE
Bug in abc.calc

### ISSUE THREAD

**Issue by chr1swallace** [chr1swallace/GUESSFM#7]
I thought I would feedback something about the approximate bayes factor calculation feature abc.calc in GUESSFM: I think it gets confused when there is missing data in the response vector, y.  When I fit the model without removing missing values, I get messages like the following:

```
"Dropping 124 samples due to incompleteness. 5163 remain.
Error in cbind(x2[, snps[[i]], drop = FALSE], qm) : 
 number of rows of matrices must match (see arg 2)"

[11:18] 
```

But when I drop the missing values manually, there is no such issue.

**Comment by jinshaw16** [comment]
Just to let you know, the issue appears to be in the internal function "abf.speedglm.fit".

The lines:
    qm <- matrix(1,nrow=nrow(x),ncol=1,dimnames=list(NULL,"one"))

and
logn <- log(nrow(x))

should perhaps read:
qm <- matrix(1,nrow=nrow(x2),ncol=1,dimnames=list(NULL,"one"))
and
logn <- log(nrow(x2))
,respectively.

The code should(!) then run.

**Comment by chr1swallace** [comment]
Thanks, why don't you try it? Clone my package on github, make your changes, then push to my repo. That way you get credited for the change!

On 31 March 2016 10:40:22 BST, jinshaw16 notifications@github.com wrote:

> Just to let you know, the issue appears to be in the internal function
> "abf.speedglm.fit".
> 
> The lines:
>    qm <- matrix(1,nrow=nrow(x),ncol=1,dimnames=list(NULL,"one"))
> 
> and
> logn <- log(nrow(x))
> 
> should perhaps read:
> qm <- matrix(1,nrow=nrow(x2),ncol=1,dimnames=list(NULL,"one"))
> and
> logn <- log(nrow(x2))
> ,respectively.
> 
> The code should(!) then run.
> 
> ---
> 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/chr1swallace/GUESSFM/issues/7#issuecomment-203854367

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
