### ISSUE TITLE
No prior plot with pp.nsnp

### ISSUE THREAD

**Issue by jinshaw16** [chr1swallace/GUESSFM#8]
As I understand it, a prior distribution line should appear in the graph if I use the option "expected=" in the  pp.nsnp command.  I have attempted this on a few different datasets and the prior line does not appear (but the y axis is labelled "Prior/Posterior probability", and the "Prior" label appears in the legend).

Having inspected the issue, it seems to be that, due to specifying no over-dispersion parameter, it defaults to 1, which defaults the "rho" parameter in the dbetabinom command to 0 as part of the pp.snp command.  Under the help for dbetabinom, it states that the rho parameter should be in the range (0,1), but that "the value 0 is sometimes supported".  

In my system, the 0 value appears not to be supported, as NaN is produced for the prior results.  When I manually change the rho parameter to a very small value, the prior appears.

I thought I would flag with you so you were aware.

**Comment by jinshaw16** [comment]
Something similar happens with abf2snpmod, with the problem occuring in the "snpprior" function, where the default overdispersion is set to 1.  Issues (in my programs) occur when the dbetabinom function is used with a rho = 0 (the default if overdispersion=1).

With this function, the problem is that NaN is produced for all Prior, lPP and PP in the models output, and NaN for the MPPI in the SNP output.

A work-around I am using for now is to use "overdispersion=1.000001" in order to obtain some meaningful output.

**Comment by chr1swallace** [comment]
Bug confirmed.  

```
library(GUESSFM)
mydir <-  system.file("extdata",package="GUESSFM")
(load(file.path(mydir,"simdata.RData")))
pp.nsnp(d,plot=TRUE,expected=3)
pp.nsnp(d,plot=TRUE,expected=3,overdispersion=1.001)
```
